apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuery-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: kuery
          servicePort: 8080
  tls:
    - secretName: kuery-tls-cert
      hosts:
      - localhost
